# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jc-matica',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/jc-matica',
                'lib_path': 'jc_matica'},
  'syms': { 'jc_matica.core': { 'jc_matica.core.ApiClient': ('core.html#apiclient', 'jc_matica/core.py'),
                                'jc_matica.core.ApiClient.__init__': ('core.html#apiclient.__init__', 'jc_matica/core.py'),
                                'jc_matica.core.ApiClient.upload': ('core.html#apiclient.upload', 'jc_matica/core.py')}}}
